version: '3'

services:
  db-user:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=monorepo-user
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=1234
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - 3306:3306
  rabbitmq:
    image: rabbitmq:3.7.5-management
    hostname: app-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-cookie
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
  user-service:
    build:
      context: .
      dockerfile: ./docker/user/Dockerfile.dev
    environment:
      - DB_HOST=db-user
      - DB_NAME=monorepo-user
      - DB_USER=test_user
      - DB_PASSSWORD=1234
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - ./:/home/app/
    depends_on:
      - rabbitmq
      - db-user
  monorepo-practice:
    build:
      context: .
      dockerfile: ./docker/monorepo-practice/Dockerfile.dev
    environment:
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - ./:/home/app/
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
      - user-service

volumes:
  mysql_volume:
