version: '3'

services:
  db-user:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=monorepo-user
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=1234
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: redis:5.0-alpine
  user-service:
    build:
      context: .
      dockerfile: ./docker/user/Dockerfile.dev
    environment:
      - DB_HOST=db-user
      - DB_NAME=monorepo-user
      - DB_USER=test_user
      - DB_PASSSWORD=1234
      - REDIS_HOST=redis
    volumes:
      - ./:/home/app/
    depends_on:
      - redis
      - db-user
  monorepo-practice:
    build:
      context: .
      dockerfile: ./docker/monorepo-practice/Dockerfile.dev
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./:/home/app/
    ports:
      - 3000:3000
    depends_on:
      - redis
      - user-service

volumes:
  mysql_volume:
